/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ServiceInstanceMetadata struct {
	Labels map[string]interface{} `json:"labels,omitempty"`

	Attributes map[string]interface{} `json:"attributes,omitempty"`
}
